version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      # ignore minor updates for stable crates that have reached 1.0
      - dependency-name: "tokio"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "url"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "bytes"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "thiserror"
        update-types: ["version-update:semver-minor"]
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "chore"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: "chore"
