# configuration for https://github.com/crate-ci/committed

# https://www.conventionalcommits.org
style = "conventional"
# we can be lenient with formatting since we're going to squash merge anyway
merge_commit = true
subject_capitalized = false
imperative_subject = false
subject_not_punctuated = false
# disable line length
line_length = 0
# disable subject length
subject_length = 0
# default allowed_types [ "chore", "docs", "feat", "fix", "perf", "refactor", "style", "test" ]
allowed_types = [
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
]
