name: "Build on nightly"
permissions:
  contents: read
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-nightly:
    name: "Build with Nightly"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: build
        run: cargo +nightly build --all-features
